### ISSUE TITLE
Debianized version of this guide

### ISSUE THREAD

**Issue by alnesbit** [rharmonson/richtech#13]
Hi, this wiki is just the sort of thing I've been search for a long time. Thank you, I love it!

The OSVDC seems pretty tied to CentOS and FreeNAS.  As I normally run Debian, I wonder if there's a version of the wiki, or any plans to add to add instructions, so that virtualization with the oVirt Virt. Appliance is shown to be feasble?

What do you think of this idea?  Thanks!

**Comment by rharmonson** [comment]
A fascinating idea!

You are correct much of the series is based on upstream Red Hat projects; oVirt, Spacewalk, FreeIPA, and so forth. This is primarily because I am a Red Hat Certified Engineer, 2001. Time and equipment is the other issue but my experience with Debian has been positive. Nothing beyond having to learn the nuances of a new distribution.

If you want to work together to tackle the endeavor, I am open to discussing it. Do you have the equipment? Have you checked to see if Debian has oVirt packages or would we look at a different management tool all together?

Where would you like to start?

Richard

**Comment by rharmonson** [comment]
Closing issue due to no response. Please reopen if you want to collaborate. Thank you.
